version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - "4000"
    ports:
      - "4000:4000"
